spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/gulozge/config-server-t1.git
server:
  port: 8888
